name: Test Actions

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-get-employee-js-action:
    name: Test Get Employee Action (JavaScript)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: get-employee-js-action/.nvmrc
          cache-dependency-path: get-employee-js-action
          cache: npm
          
      - name: Install Dependencies
        run: npm ci
        working-directory: get-employee-js-action
        
      - name: Test Get Employee (JavaScript) Action
        id: test-employee-js-action
        uses: ./get-employee-js-action
        with:
          github-username: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-token: ${{ secrets.SLACK_TOKEN }}
          
      - name: Print Slack User ID
        run: echo "${{ steps.test-employee-js-action.outputs.slack-user-id }}"

  test-get-employee-docker-action:
    name: Test Get Employee Action (Docker)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test Get Employee (Docker) Action
        id: test-employee-docker-action
        uses: ./get-employee-docker-action
        with:
          github-username: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-token: ${{ secrets.SLACK_TOKEN }}
          
      - name: Print Slack User ID
        run: echo "${{ steps.test-employee-docker-action.outputs.slack-user-id }}"

  test-send-message-composite-action:
    name: Test Send Slack Action (Composite)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: get-employee-js-action/.nvmrc
          cache-dependency-path: get-employee-js-action
          cache: npm
          
      - name: Install Dependencies
        run: npm ci
        working-directory: get-employee-js-action
        
      - name: Test Slack Message (Composite) Action
        id: test-send-action
        uses: ./
        with:
          github-username: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          
      - name: Print Slack Message Time
        run: echo "${{ steps.test-send-action.outputs.time }}"

